export const nationalities: {[short: string]: string} = {
    'AFG': 'Afghanistan',
    'AGO': 'Angola',
    'AIA': 'Anguilla',
    'ALB': 'Albania',
    'ALG': 'Algeria',
    'AND': 'Andorra',
    'ANT': 'Netherlands Antilles',
    'ARE': 'United Arab Emirates',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ASA': 'American Samoa',
    'ATA': 'Antarctica',
    'ATF': 'French Southern Territories',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BAH': 'Bahamas',
    'BAR': 'Barbados',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benin',
    'BER': 'Bermuda',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'BIH': 'Bosnia and Herzegovina',
    'BLR': 'Belarus',
    'BLZ': 'Belize',
    'BOL': 'Bolivia',
    'BRA': 'Brazil',
    'BRN': 'Brunei Darussalam',
    'BTN': 'Bhutan',
    'BUL': 'Bulgaria',
    'BVT': 'Bouvet Island',
    'BWA': 'Botswana',
    'CAF': 'Central African Republic',
    'CAN': 'Canada',
    'CAY': 'Cayman Island',
    'CCK': 'Cocos Islands',
    'CHI': 'Chile',
    'CHN': 'China',
    'CIV': 'Côte D\'Ivoire',
    'CMR': 'Cameroon',
    'COD': 'Congo',
    'COG': 'Congo',
    'COK': 'Cook Islands',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'CPV': 'Cape Verde',
    'CRC': 'Costa Rica',
    'CRO': 'Croatia',
    'CUB': 'Cuba',
    'CXR': 'Christmas Island',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DEN': 'Denmark',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DOM': 'Dominican Republic',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ERI': 'Eritrea',
    'ESA': 'El Salvador',
    'ESH': 'Western Sahara',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FIJ': 'Fiji',
    'FIN': 'Finland',
    'FLK': 'Falkland Islands',
    'FRA': 'France',
    'FRO': 'Faroe Islands',
    'FSM': 'Micronesia',
    'GAB': 'Gabon',
    'GBR': 'United Kingdom',
    'GEO': 'Georgia',
    'GER': 'Germany',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GIN': 'Guinea',
    'GLP': 'Guadeloupe',
    'GMB': 'Gambia',
    'GNB': 'Guinea-Bissau',
    'GNQ': 'Equatorial Guinea',
    'GRE': 'Greece',
    'GRL': 'Greenland',
    'GUA': 'Guatemala',
    'GUF': 'French Guiana',
    'GUM': 'Guam',
    'GUY': 'Guyana',
    'HAI': 'Haiti',
    'HKG': 'Hong Kong',
    'HMD': 'Heard And Mc Donald Islands',
    'HON': 'Honduras',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IOP': 'Independent Olympic Participants',
    'IOT': 'British Indian Ocean Territory',
    'IRI': 'Iran',
    'IRL': 'Ireland',
    'IRQ': 'Iraq',
    'ISL': 'Iceland',
    'ISR': 'Israel',
    'ISV': 'U.s. Virgin Islands',
    'ITA': 'Italy',
    'IVB': 'British Virgin Islands',
    'JAM': 'Jamaica',
    'JOR': 'Jordan',
    'JPN': 'Japan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyzstan',
    'KHM': 'Cambodia',
    'KIR': 'Kiribati',
    'KNA': 'St Kitts and Nevis',
    'KOR': 'South Korea',
    'KOS': 'Kosovo',
    'KUW': 'Kuwait',
    'LAO': 'Laos',
    'LAT': 'Latvia',
    'LBR': 'Liberia',
    'LBY': 'Libyan Arab Jamahiriya',
    'LCA': 'Saint Lucia',
    'LES': 'Lesotho',
    'LBN': 'Lebanon',
    'LIE': 'Liechtenstein',
    'LKA': 'Sri Lanka',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'MAC': 'Macau',
    'MAD': 'Madagascar',
    'MAR': 'Marocco',
    'MAS': 'Malaysia',
    'MDA': 'Moldova',
    'MDV': 'Maldives',
    'MEX': 'Mexico',
    'MGL': 'Mongolia',
    'MHL': 'Marshall Islands',
    'MKD': 'Macedonia',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MMR': 'Myanmar',
    'MNE': 'Montenegro',
    'MNP': 'Northern Mariana Islands',
    'MON': 'Monaco',
    'MOZ': 'Mozambique',
    'MRT': 'Mauritania',
    'MSR': 'Montserrat',
    'MTQ': 'Martinique',
    'MUS': 'Mauritius',
    'MWI': 'Malawi',
    'MYT': 'Mayotte',
    'NAM': 'Namibia',
    'NCL': 'New Caledonia',
    'NED': 'Netherlands',
    'NEP': 'Nepal',
    'NER': 'Niger',
    'NFK': 'Norfolk Island',
    'NGA': 'Nigeria',
    'NIC': 'Nicaragua',
    'NIU': 'Niue',
    'NOR': 'Norway',
    'NRU': 'Nauru',
    'NZL': 'New Zealand',
    'OMN': 'Oman',
    'PAK': 'Pakistan',
    'PAN': 'Panama',
    'PAR': 'Paraguay',
    'PCN': 'Pitcairn',
    'PER': 'Peru',
    'PHI': 'Philippines',
    'PLE': 'Palestine',
    'PLW': 'Palau',
    'PNG': 'Papua New Guinea',
    'POL': 'Poland',
    'POR': 'Portugal',
    'PRK': 'North Korea',
    'PUR': 'Puerto Rico',
    'PYF': 'French Polynesia',
    'QAT': 'Qatar',
    'REU': 'Reunion',
    'ROU': 'Romania',
    'RSA': 'South Africa',
    'RSM': 'San Marino',
    'RUS': 'Russia',
    'RWA': 'Rwanda',
    'SAU': 'Saudi Arabia',
    'SCG': 'Serbia and Montenegro',
    'SEN': 'Senegal',
    'SGP': 'Singapore',
    'SHN': 'St. Helena',
    'SJM': 'Svalbard And Jan Mayen Islands',
    'SLB': 'Solomon Islands',
    'SLE': 'Sierra Leone',
    'SLO': 'Slovenia',
    'SOM': 'Somalia',
    'SPA': 'Spain',
    'SPM': 'St. Pierre And Miquelon',
    'SRB': 'Serbia',
    'STP': 'Sao Tome And Principe',
    'SUD': 'Sudan',
    'SUI': 'Switzerland',
    'SUR': 'Suriname',
    'SVK': 'Slovakia',
    'SWE': 'Sweden',
    'SWZ': 'Swaziland',
    'SYC': 'Seychelles',
    'SYR': 'Syrian Arab Republic',
    'TCA': 'Turks And Caicos Islands',
    'TCD': 'Chad',
    'TGA': 'Tonga',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TKL': 'Tokelau',
    'TKM': 'Turkmenistan',
    'TLS': 'Timor-Leste',
    'TOG': 'Togo',
    'TPE': 'Chinese Taipei',
    'TRI': 'Trinidad and Tobago',
    'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'TUV': 'Tuvalu',
    'TZA': 'Tanzania',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'URU': 'Uruguay',
    'USA': 'United States',
    'UZB': 'Uzbekistan',
    'VAT': 'Vatican City',
    'VCT': 'Saint Vincent And The Grenadines',
    'VEN': 'Venezuela',
    'VNM': 'Vietnam',
    'VUT': 'Vanuatu',
    'WLF': 'Wallis And Futuna Islands',
    'YEM': 'Yemen',
    'ZIM': 'Zimbabwe',
    'ZMB': 'Zambia'
};

export const WeatherConditions: {[status: string]: number} = {
    'sun': 1,
    'pcl': 2,
    'clo': 3,
    'sno': 4,
    'rai': 5,
    'fog': 6
};

export const WindConditions: {[status: string]: number} = {
    'no': 1,
    'lo': 2,
    'me': 3,
    'hi': 4
};

export const SnowConditions: {[short: string]: string} = {
    'sft': 'Soft',
    'wtpwd': 'Wet & powder',
    'wt_pwd': 'Wet & powder',
    'wt': 'Wet',
    'cmp': 'Compact',
    'f_g': 'Fine grained',
    'grn': 'Granular',
    'hrd': 'Hard',
    'hrd_p': 'Hard packed',
    'hrd_p_v': 'Hard packed variable',
    'icy': 'Icy',
    'p': 'Packed',
    'ppwd': 'Packed powder',
    'pwd': 'Powder',
    'sp_c': 'Spring conditions',
    'salt': 'Salt'
};

export const maxVal = 1000000000;

export const statusMap: {[status: string]: string} = {
    'start': 'Started',
    'finish': 'Finished',
    'lapped': 'Lapped',
    'nextstart': 'Next to start',
    'ral': 'RAL',
    'dnf': 'DNF',
    'dq': 'DQ',
    'dns': 'DNS'
};

export const timeToStatusMap: {[time: number]: string} = {
    [maxVal + 1]: 'RAL',
    [maxVal * 2]: 'Lapped',
    [maxVal * 3]: 'DNF',
    [maxVal * 4]: 'DQ',
    [maxVal * 5]: 'DNS',
    [maxVal * 6]: 'N/A'
};

export const statusToTimeMap: {[status: string]: number} = {
    'ral':      maxVal + 1,
    'lapped':   maxVal * 2,
    'dnf':      maxVal * 3,
    'dq':       maxVal * 4,
    'dns':      maxVal * 5,
    'N/A':      maxVal * 6
};
